import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import useSWR from 'swr';
import {
  useConnectModal,
  useAccountModal,
  useChainModal,
} from '@rainbow-me/rainbowkit';
import { Auction } from '../components/Auction';
import { useEthers } from '@usedapp/core';
import { fetchAlchemy } from '../data/fetch/fetchAlchemy';
import { useEffect, useState } from 'react';

import Logo from '../public/assets/images/Logo';
import { NftsContent } from '../components/NftsContent';

const ALCHEMY_URL = 'https://eth-mainnet.g.alchemy.com/nft/v2/';

export default function Home(context) {
  const { data } = useSWR(ALCHEMY_URL, fetchAlchemy);
  const [connected, setConnected] = useState(false);
  const { account } = useEthers();
  const { openConnectModal } = useConnectModal();
  const { openAccountModal } = useAccountModal();
  const { openChainModal } = useChainModal();

  useEffect(() => {
    if (account) {
      setConnected(true);
    } else {
      setConnected(false);
    }
  }, [account]);

  return (
    <>
      <div className={styles.container} data-theme='fantasy'>
        <Head>
          <title>Remint Demo</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Header />

        <div
          className='hero min-h-screen bg-base-200 px-1000 h-screen'
          style={{ backgroundColor: '#000000' }}
        >
          <div className='hero-content flex-col ' style={{ width: '80%' }}>
            <Logo style={{ fontSize: '59rem' }} />
            <div className='flex text-white justify-center text-2xl mt-12 mb-10'>
              RETURNING VALUE TO YOUR FORGOTTEN NFTs
            </div>
            <div className='flex justify-center' style={{ color: '#fff' }}>
              {connected ? (
                <>
                  <button
                    className='btn btn-sm btn-outline btn-primary ml-3 normal-case'
                    style={{ color: '#fff' }}
                    onClick={openAccountModal}
                  >
                    Profile
                  </button>
                  <button
                    className='btn btn-sm btn-outline btn-primary ml-3 normal-case'
                    style={{ color: '#fff' }}
                    onClick={openChainModal}
                  >
                    Chains
                  </button>
                </>
              ) : (
                <button
                  className='btn btn-sm btn-outline btn-primary ml-3 normal-case'
                  onClick={openConnectModal}
                >
                  connect wallet
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
      {connected && <Auction />}
      {connected && <NftsContent cards={data} />}
    </>
  );
}
